version: "2"

linters:
  enable:
    - lll       # Checks line length
    - errcheck  # Checks for unhandled errors
    - revive    # General style and code quality rules

linters-settings:
  lll:
    line-length: 120
