apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unseal-vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unseal-vault
subjects:
  - kind: ServiceAccount
    name: unseal-vault
    namespace: job
