apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  namespace: monitoring
spec:
  capacity:
    storage: 50Gi
  volumeMode: FileSystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/dat-phu/k8s/prometheus/persistent-volume
