apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: monitoring
spec:
  accessModel:
    - ReadWriteOnce
  resources:
    request:
      storage: 50Gi
  storageClassName: ""
