apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
 name: vault-example
spec:
 refreshInterval: "10s"
 secretStoreRef:
  name: vault-backend
  kind: ClusterSecretStore
 target:
  name: example-sync
 data:
 - secretKey: foobar
   remoteRef:
    key: foo
    property: my-value

 - secretKey: tags
   remoteRef:
    metadataPolicy: Fetch
    key: foo

 - secretKey: developer
   remoteRef:
    metadataPolicy: Fetch
    key: foo
    property: dev
