apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-ssh-key
  namespace: app
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-ssh-key
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "auth": "{{ printf "%s" .key | b64enc }}"
              }
            }
          }
  data:
    - secretKey: key
      remoteRef:
        key: github_ssh_key
        property: private
